"""Codegen agent — generates a runnable FastAPI service from an OpenAPI 3.1 spec.

Emits real, readable Python source (not a runtime interpreter of the spec):
* pydantic models for every component schema, topologically ordered so nested
  references resolve without forward-ref juggling, each with an ``example()``
  factory that yields a schema-valid instance;
* a FastAPI app with one stub handler per operation (returning that example),
  a ``/health`` endpoint, and an ``X-Served-By`` header so the strangler demo
  can prove which backend answered.
"""
from __future__ import annotations

import re
from typing import Any


class CodegenAgent:
    def __init__(self, spec: dict, service_slug: str) -> None:
        self.spec = spec
        self.slug = service_slug
        self.schemas: dict[str, dict] = spec.get("components", {}).get("schemas", {})

    # ------------------------------------------------------------------ #
    def generate(self) -> dict[str, str]:
        return {
            "__init__.py": "",
            "models.py": self._models_source(),
            "main.py": self._app_source(),
            "requirements.txt": "fastapi>=0.110\nuvicorn[standard]>=0.29\npydantic>=2.6\n",
        }

    # ---- models ------------------------------------------------------ #
    def _models_source(self) -> str:
        order = self._topo_order()
        blocks = [self._model_class(name) for name in order]
        header = (
            '"""Pydantic models generated from the OpenAPI contract.\n\n'
            "AUTO-GENERATED by agents/codegen_agent.py — do not edit by hand.\n"
            '"""\n'
            "from __future__ import annotations\n\n"
            "from pydantic import BaseModel\n\n"
        )
        if not blocks:
            blocks = ["# (this service exposes no component schemas)\n"]
        return header + "\n\n".join(blocks) + "\n"

    def _topo_order(self) -> list[str]:
        """Define referenced schemas before the schemas that reference them."""
        order: list[str] = []
        seen: set[str] = set()

        def visit(name: str) -> None:
            if name in seen or name not in self.schemas:
                return
            seen.add(name)
            for dep in sorted(self._refs_of(self.schemas[name])):
                visit(dep)
            order.append(name)

        for name in sorted(self.schemas):
            visit(name)
        return order

    def _refs_of(self, schema: dict) -> set[str]:
        refs: set[str] = set()

        def walk(node: Any) -> None:
            if isinstance(node, dict):
                if "$ref" in node:
                    refs.add(node["$ref"].split("/")[-1])
                for v in node.values():
                    walk(v)
            elif isinstance(node, list):
                for v in node:
                    walk(v)

        walk(schema)
        return refs

    def _model_class(self, name: str) -> str:
        schema = self.schemas[name]
        props: dict[str, dict] = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines = [f"class {name}(BaseModel):"]
        if not props:
            lines.append("    pass")
        field_examples: list[str] = []
        for field, fschema in props.items():
            annotation, optional = self._annotation(fschema)
            if optional or field not in required:
                lines.append(f"    {field}: {annotation} | None = None")
            else:
                lines.append(f"    {field}: {annotation}")
            field_examples.append(f"{field}={self._example_expr(fschema, field in required)}")
        # example() factory
        lines.append("")
        lines.append("    @classmethod")
        lines.append(f'    def example(cls) -> "{name}":')
        if field_examples:
            args = ", ".join(field_examples)
            lines.append(f"        return cls({args})")
        else:
            lines.append("        return cls()")
        return "\n".join(lines)

    # ---- app --------------------------------------------------------- #
    def _app_source(self) -> str:
        service_title = self.spec.get("info", {}).get("title", self.slug)
        handlers: list[str] = []
        registrations: list[str] = []
        for path, item in self.spec.get("paths", {}).items():
            for method, op in item.items():
                fn, reg = self._handler(path, method, op)
                handlers.append(fn)
                registrations.append(reg)

        model_names = ", ".join(self._topo_order()) or ""
        import_models = f"from models import {model_names}\n" if model_names else ""
        body = "\n\n".join(handlers)
        regs = "\n".join(registrations)
        return f'''"""FastAPI skeleton for the {service_title}.

AUTO-GENERATED by agents/codegen_agent.py from the OpenAPI 3.1 contract.
Stub handlers return schema-conformant example payloads; replace their bodies
with real logic as the service is fleshed out.
"""
from __future__ import annotations

from fastapi import Body, FastAPI, Request, Response

{import_models}
app = FastAPI(title="{service_title}")
SERVICE = "{self.slug}-service"


@app.middleware("http")
async def _served_by(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Served-By"] = SERVICE
    return response


@app.get("/health")
def health() -> dict:
    return {{"status": "ok", "service": SERVICE}}


{body}


{regs}
'''

    def _handler(self, path: str, method: str, op: dict) -> tuple[str, str]:
        op_id = op.get("operationId") or _safe_name(f"{method}_{path}")
        params = op.get("parameters", [])
        sig_params: list[str] = []
        for p in params:
            ptype = "int" if p.get("schema", {}).get("type") == "integer" else "str"
            sig_params.append(f"{p['name']}: {ptype}")
        if method.lower() in {"post", "put", "patch"}:
            sig_params.append("payload: dict = Body(default_factory=dict)")

        status, expr = self._response_example(op)
        sig = ", ".join(sig_params)
        decorator_path = path
        fn = (
            f"def {op_id}({sig}):\n"
            f"    return {expr}"
        )
        status_kw = f", status_code={status}" if status not in (200, None) else ""
        reg = (
            f'app.add_api_route("{decorator_path}", {op_id}, '
            f'methods=["{method.upper()}"]{status_kw})'
        )
        return fn, reg

    def _response_example(self, op: dict) -> tuple[int, str]:
        responses = op.get("responses", {})
        # pick the success status (2xx) with the lowest code
        code = min((int(c) for c in responses if str(c).startswith("2")), default=200)
        schema = (
            responses.get(str(code), {})
            .get("content", {})
            .get("application/json", {})
            .get("schema")
        )
        if schema is None:
            return code, '{"status": "ok"}'
        return code, self._example_expr(schema, required=True)

    # ---- schema -> python -------------------------------------------- #
    def _annotation(self, schema: dict) -> tuple[str, bool]:
        if "$ref" in schema:
            return schema["$ref"].split("/")[-1], False
        if "anyOf" in schema:
            subs = [s for s in schema["anyOf"] if s.get("type") != "null"]
            optional = any(s.get("type") == "null" for s in schema["anyOf"])
            ann, _ = self._annotation(subs[0]) if subs else ("Any", True)
            return ann, optional
        t = schema.get("type")
        if t == "array":
            item_ann, _ = self._annotation(schema.get("items", {}))
            return f"list[{item_ann}]", False
        return {"integer": "int", "number": "float", "string": "str",
                "boolean": "bool", "object": "dict", "null": "None"}.get(t, "dict"), False

    def _example_expr(self, schema: dict, required: bool) -> str:
        if "$ref" in schema:
            return f"{schema['$ref'].split('/')[-1]}.example()"
        if "anyOf" in schema:
            subs = [s for s in schema["anyOf"] if s.get("type") != "null"]
            if any(s.get("type") == "null" for s in schema["anyOf"]):
                return "None"
            return self._example_expr(subs[0], required) if subs else "None"
        t = schema.get("type")
        if t == "array":
            return f"[{self._example_expr(schema.get('items', {}), True)}]"
        return {"integer": "0", "number": "0.0", "string": '"stub"',
                "boolean": "False", "object": "{}", "null": "None"}.get(t, "None")


def _safe_name(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", text).strip("_") or "op"
