"""Routing agent — generates the strangler-fig gateway.

Emits a config-driven FastAPI gateway: a YAML route table maps URL prefixes to
backends, extracted routes go to the new microservice and everything else falls
through to the still-running monolith. The forwarding app is built by a factory
that accepts injected HTTP clients, so the topology is testable in-process
(httpx WSGI/ASGI transports) without Docker.
"""
from __future__ import annotations

import yaml

from core.context_pack import ApprovedDecomposition, RepoAnalysis


class RoutingAgent:
    def __init__(self, analysis: RepoAnalysis, approved: ApprovedDecomposition) -> None:
        self.analysis = analysis
        self.approved = approved
        self.by_module = analysis.pack_by_module()

    # ------------------------------------------------------------------ #
    def route_table(self) -> dict:
        target = self.approved.extraction_target
        service = next((s for s in self.approved.services if s.name == target), None)
        prefixes = sorted(self._prefixes(service.modules)) if service else []
        backend = f"{_slug(target).lower()}-service"
        return {
            "default_backend": "monolith",
            "backends": {
                "monolith": "${MONOLITH_URL}",
                backend: "${" + _slug(target).upper() + "_URL}",
            },
            "routes": [{"prefix": p, "backend": backend} for p in prefixes],
        }

    def _prefixes(self, modules: list[str]) -> set[str]:
        prefixes: set[str] = set()
        for m in modules:
            pack = self.by_module.get(m)
            if pack is None:
                continue
            if pack.url_prefix:
                prefixes.add(pack.url_prefix)
            else:
                for r in pack.routes:
                    seg = r.path.split("/")[1] if "/" in r.path.strip("/") else r.path
                    prefixes.add("/" + r.path.strip("/").split("/")[0])
        return {p for p in prefixes if p and p != "/"}

    # ------------------------------------------------------------------ #
    def generate(self) -> dict[str, str]:
        table = self.route_table()
        return {
            "__init__.py": "",
            "routes.yaml": yaml.safe_dump(table, sort_keys=False),
            "routing.py": _ROUTING_PY,
            "main.py": _MAIN_PY,
            "requirements.txt": "fastapi>=0.110\nuvicorn[standard]>=0.29\nhttpx>=0.27\nPyYAML>=6.0\n",
        }


# --------------------------------------------------------------------------- #
# Emitted gateway source (static logic; the route table is data-driven)
# --------------------------------------------------------------------------- #
_ROUTING_PY = '''"""Strangler-fig gateway core.

AUTO-GENERATED by agents/routing_agent.py. The route table (routes.yaml) maps
URL prefixes to backends; unmatched paths fall through to the monolith. The
proxy forwards each request to the resolved backend through an async "sender".
In production every sender is an ``httpx.AsyncClient`` pointed at a real URL; in
tests, senders wrap the in-process apps (ASGI for the new service, a threaded
WSGI shim for the Flask monolith) so the whole topology runs without Docker.
"""
from __future__ import annotations

import os
from contextlib import asynccontextmanager
from pathlib import Path

import httpx
import yaml
from fastapi import FastAPI, Request, Response

CONFIG_PATH = Path(__file__).with_name("routes.yaml")


def load_route_table(path: Path = CONFIG_PATH) -> dict:
    table = yaml.safe_load(path.read_text())
    defaults = {"MONOLITH_URL": "http://monolith:8000"}
    for name, url in list(table.get("backends", {}).items()):
        if isinstance(url, str) and url.startswith("${") and url.endswith("}"):
            env = url[2:-1]
            table["backends"][name] = os.environ.get(
                env, defaults.get(env, "http://" + name + ":8000")
            )
    return table


def resolve_backend(path: str, table: dict) -> str:
    """First matching prefix wins (longest prefix first); else the default."""
    for route in sorted(table.get("routes", []), key=lambda r: -len(r["prefix"])):
        prefix = route["prefix"]
        if path == prefix or path.startswith(prefix + "/"):
            return route["backend"]
    return table.get("default_backend", "monolith")


def build_gateway_app(table: dict | None = None, senders: dict | None = None) -> FastAPI:
    """Build the gateway. ``senders`` maps backend-name -> an object with an
    async ``request(method, url, params, content, headers) -> httpx.Response``.
    When None, one ``httpx.AsyncClient`` per backend is built from the table."""
    table = table or load_route_table()
    owns = senders is None
    if senders is None:
        senders = {
            name: httpx.AsyncClient(base_url=url, timeout=10.0)
            for name, url in table["backends"].items()
        }

    @asynccontextmanager
    async def lifespan(app):
        yield
        if owns:
            for s in senders.values():
                await s.aclose()

    app = FastAPI(title="Strangler Gateway", lifespan=lifespan)

    @app.get("/__gateway/health")
    def gateway_health() -> dict:
        return {"status": "ok", "service": "gateway", "routes": table["routes"],
                "backends": list(table["backends"])}

    @app.api_route("/{full_path:path}",
                   methods=["GET", "POST", "PUT", "PATCH", "DELETE"])
    async def proxy(full_path: str, request: Request) -> Response:
        path = "/" + full_path
        backend = resolve_backend(path, table)
        body = await request.body()
        upstream = await senders[backend].request(
            request.method, path,
            params=dict(request.query_params),
            content=body,
            headers={k: v for k, v in request.headers.items()
                     if k.lower() not in {"host", "content-length"}},
        )
        headers = {"X-Gateway-Backend": backend}
        if "x-served-by" in upstream.headers:
            headers["X-Served-By"] = upstream.headers["x-served-by"]
        return Response(content=upstream.content, status_code=upstream.status_code,
                        headers=headers,
                        media_type=upstream.headers.get("content-type"))

    return app
'''

_MAIN_PY = '''"""Gateway entrypoint. AUTO-GENERATED by agents/routing_agent.py."""
from routing import build_gateway_app

app = build_gateway_app()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8080)
'''


def _slug(name: str) -> str:
    import re

    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")
